### ISSUE TITLE
Message d’erreur : « Chain validation failed »

### ISSUE THREAD

**Issue by Bagu** [hobgoblinsmaster/fbxapitoavahi#1]
Bonjour,

Disposant d'un serveur Nas Synology, j'ai installé python3, créé le fichier apitoavahi.py et lancé le tout en ssh : 
`sudo /usr/local/bin/python3 /volume1/homes/monnimdutilisateur/apitoavahi.py /etc/avahi/services/fbx.service`
Tout s'exécute sans erreur et le fichier se créé sans soucis : 

`<service-group>
        <name replace-wildcards="yes">Freebox Server</name>
        <service protocol="ipv4">
                <type>_fbx-api._tcp</type>
                <port>80</port>
                <host-name>mafreebox.freebox.fr</host-name>
                <txt-record>device_type=FreeboxServer1,1</txt-record>
                <txt-record>api_version=6.0</txt-record>
                <txt-record>api_domain=wzlej8sw.fbxos.fr</txt-record>
                <txt-record>box_model=fbxgw-r1/full</txt-record>
                <txt-record>https_port=59999</txt-record>
                <txt-record>uid=57cff8b08672542011b59aa5650a450b</txt-record>
                <txt-record>https_available=True</txt-record>
                <txt-record>box_model_name=Freebox Server (r1)</txt-record>
                <txt-record>api_base_url=/api/</txt-record>
                <txt-record>device_name=Freebox Server</txt-record>
        </service>
</service-group>`

Cependant, en lançant l'association, tout se passe bien, jusqu'à la finb où je reçois le message "chain validation failed"

Auriez-vous une idée de ce qu'il se passe ?

**Comment by hobgoblinsmaster** [comment]
La demande d’association s’affiche-t-elle sur la box ?
Que vois une application comme « [Service Browser](https://play.google.com/store/apps/details?id=com.druk.servicebrowser) » sur le téléphone ?
Si le fichier est bon et le service visible correctement sur le réseau, je ne pense pas pouvoir faire grand chose à mon niveau.

**Comment by Bagu** [comment]
Bonjour,

La demande d'association apparait bien.
Je reçois ce message sur le téléphone juste après.

Service browser n'affiche rien du tout, mais je ne suis pas sûr de l'utiliser correctement.

**Comment by hobgoblinsmaster** [comment]
Pouvez-vous tenter de lancer :
`avahi-browse -rv _fbx-api._tcp`
Depuis une machine Linux (avahi doit être installé).

**Comment by Bagu** [comment]
Je n'ai à disposition que le serveur NAS sous linux.
Sur le serveur la commande sort bien les bonnes informations.
Dois-je lancer cela sur une autre machine obligatoirement ?

**Comment by hobgoblinsmaster** [comment]
>  Dois-je lancer cela sur une autre machine obligatoirement ?

Non, n’importe quelle machine du LAN doit pouvoir faire l’affaire.

Si les infos sont bonnes, il doit y avoir autre chose, essayez de poser la question sur la page du bug freebox : https://dev.freebox.fr/bugs/task/22301

**Comment by Bagu** [comment]
Bonjour,

J'ai été radical : 
-Suppression du cache et des données utilisateur de l'appli du téléphone
-Suppression de l'appli du téléphone
-Révocation des accès sur la freebox
-Reboot de la freebox
-Lancement du script
-Installation de l'appli sur le téléphone

Et cela fonctionne !
Bon, il me reste un soucis mais qui ne doit pas être lié...En fait au lancement de l'appli, j'ai un failed to connect to /monip:monport
Mais quand j'appui sur ma freebox dans la liste, cela se connecte sans soucis.

Je suspecte un problème avec la config de mon routeur (peut être un poil trop verrouillé) mais rien à voir avec le script qui fonctionne à merveille.

Merci pour tout ;)

**Comment by hobgoblinsmaster** [comment]
Content que ce soit résolu, merci du retour.
